name: reddit_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  any_link_preview: ^3.0.1
  cloud_firestore: ^4.15.7
  dotted_border: ^2.1.0
  file_picker: ^6.2.0
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  firebase_storage: ^11.6.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  fpdart: ^1.1.0
  google_sign_in: ^6.2.1
  routemaster: ^1.0.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
