name: reddit_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
  # class_name: Assets
